"use client";

import { useMemo } from "react";
import { ChartHoverContext, ChartStableContext } from "./chart-contexts";

export function ChartProvider({ children, value }) {
  const stable = useMemo(() => ({
    data: value.data,
    renderData: value.renderData,
    xScale: value.xScale,
    yScale: value.yScale,
    yScales: value.yScales,
    width: value.width,
    height: value.height,
    innerWidth: value.innerWidth,
    innerHeight: value.innerHeight,
    margin: value.margin,
    columnWidth: value.columnWidth,
    containerRef: value.containerRef,
    lines: value.lines,
    referenceAreas: value.referenceAreas,
    chartPhase: value.chartPhase,
    chartStatus: value.chartStatus,
    loadingLabel: value.loadingLabel,
    yDomainTweenDuration: value.yDomainTweenDuration,
    yDomainSkeletonByAxis: value.yDomainSkeletonByAxis,
    yDomainTargetByAxis: value.yDomainTargetByAxis,
    isLoaded: value.isLoaded,
    animationDuration: value.animationDuration,
    animationEasing: value.animationEasing,
    enterTransition: value.enterTransition,
    revealEpoch: value.revealEpoch,
    notifyLoadingPulseComplete: value.notifyLoadingPulseComplete,
    xAccessor: value.xAccessor,
    dateLabels: value.dateLabels,
    xDomain: value.xDomain,
    xDomainSlotCount: value.xDomainSlotCount,
    barScale: value.barScale,
    bandWidth: value.bandWidth,
    barXAccessor: value.barXAccessor,
    orientation: value.orientation,
    stacked: value.stacked,
    stackOffsets: value.stackOffsets,
    composedBarDataKeys: value.composedBarDataKeys,
    composedBarSize: value.composedBarSize,
    composedMaxBarSize: value.composedMaxBarSize,
    composedBarGap: value.composedBarGap,
    composedStacked: value.composedStacked,
    composedStackOffsets: value.composedStackOffsets,
    composedStackGap: value.composedStackGap,
  }), [
    value.data,
    value.renderData,
    value.xScale,
    value.yScale,
    value.yScales,
    value.width,
    value.height,
    value.innerWidth,
    value.innerHeight,
    value.margin,
    value.columnWidth,
    value.containerRef,
    value.lines,
    value.referenceAreas,
    value.chartPhase,
    value.chartStatus,
    value.loadingLabel,
    value.yDomainTweenDuration,
    value.yDomainSkeletonByAxis,
    value.yDomainTargetByAxis,
    value.isLoaded,
    value.animationDuration,
    value.animationEasing,
    value.enterTransition,
    value.revealEpoch,
    value.notifyLoadingPulseComplete,
    value.xAccessor,
    value.dateLabels,
    value.xDomain,
    value.xDomainSlotCount,
    value.barScale,
    value.bandWidth,
    value.barXAccessor,
    value.orientation,
    value.stacked,
    value.stackOffsets,
    value.composedBarDataKeys,
    value.composedBarSize,
    value.composedMaxBarSize,
    value.composedBarGap,
    value.composedStacked,
    value.composedStackOffsets,
    value.composedStackGap,
  ]);

  const hover = useMemo(() => ({
    tooltipData: value.tooltipData,
    setTooltipData: value.setTooltipData,
    selection: value.selection,
    clearSelection: value.clearSelection,
    hoveredBarIndex: value.hoveredBarIndex,
    setHoveredBarIndex: value.setHoveredBarIndex,
    hoveredCandleIndex: value.hoveredCandleIndex,
    setHoveredCandleIndex: value.setHoveredCandleIndex,
  }), [
    value.tooltipData,
    value.setTooltipData,
    value.selection,
    value.clearSelection,
    value.hoveredBarIndex,
    value.setHoveredBarIndex,
    value.hoveredCandleIndex,
    value.setHoveredCandleIndex,
  ]);

  return (
    <ChartStableContext.Provider value={stable}>
      <ChartHoverContext.Provider value={hover}>
        {children}
      </ChartHoverContext.Provider>
    </ChartStableContext.Provider>
  );
}
